config/routes.rb
Zipmark::Application.routes.draw do
  devise_for :users

  resources :marks, :only => [:new, :create, :destroy]

  root :to => 'dashboard#index'

  match 'dashboard/tags/:tag' => 'dashboard#show_user_tags', as: :tag
  match 'tags/:tag' => 'dashboard#show_all_tags', as: :all_tag
  
  match '/marks/new/:title/*url' => 'marks#new', :format => false, :constraints => { :url => /.*/, :title => /.*/ }, as: :add_mark, :remote => true
end

app/models/mark.rb
class Mark < ActiveRecord::Base
  attr_accessible :tag, :title, :url, :tag_list
  belongs_to :user

  validates :url, :presence => true
  validates :title, :length => 3..140, :presence => true

  acts_as_taggable
end

app/models/tag.rb
class Tag < ActiveRecord::Base

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable, :validatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :username
  # attr_accessible :title, :body

  validates :username, :presence => true, :uniqueness => true
  validates :email, :presence => true, :uniqueness => true

  has_many :marks

  acts_as_tagger
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :lander]

  def index
    if user_signed_in?
      @marks = current_user.marks.order("created_at DESC")
    else
      render 'lander'
    end
  end

  def show_user_tags
    @tag = params[:tag]
    @marks = current_user.marks.tagged_with(@tag, :owned_by => current_user)
    render 'index'
  end

  def show_all_tags
    @tag = params[:tag]
    tag_id = Tag.find_by_name(@tag)
    @marks = Mark.find(:all,
                :joins => [:taggings],
                :conditions => ['taggings.tagger_id IS NOT NULL AND taggings.tag_id = ?', tag_id])
    render 'index'
  end

  def add_mark
    @url = params[:url]
    @title = params[:title]
  end

  def lander

  end
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  before_filter :authenticate_user!

  def new
    @mark = current_user.marks.build(params[:mark])
  end

  def create
    # using https://github.com/mbleigh/acts-as-taggable-on
    # this creates 2 relationships in the :taggings model
    # because we have to add ownership to the tag to "list as tag"
    # 

    tags = params[:mark][:tag_list]
    @mark = current_user.marks.build(params[:mark])
    if @mark.save

      # This creates the correct tags, as well as the correct ownership
      # relations, however calling this afterwards creates 2 different relationships.
      # If I don't do this, the tag wont show up in @user.owned_tags
      #
      current_user.tag(@mark, :with => tags, :on => :tags)

      flash[:notice] = "Zipmark saved!"
      if params[:remote] = true
        render :close
      else
        redirect_to root_path
      end
    else
      render :action => 'new'
    end
  end

  def destroy
    @mark = current_user.marks.find(params[:id])
    @mark.destroy

    redirect_to request.referer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div class="container">
  <% if user_signed_in? %>
    <%= render 'dashboard/shared/zip_nav' %>
    <%= render 'marks/show_marks' %>
  <% end %>
</div>

app/views/dashboard/lander.html.erb
<div class="container">
  <div class="hero-unit">
    <h1>Welcome to Zipmark.</h1>
    <h2>A place to save the things you love.</h2>

    <p>1. Come across something you love, Zipmark it using our bookmark link, and I'll save it for later.</p>
    <p>2. Categorize your zipmarks using tags.</p>
    <p>3. See what others are zipmarking within the same categories!</p><br />
    <p>
      Get started by <%= link_to "creating an account", new_user_registration_path, :class => 'btn btn-large' %> or <%= link_to "logging in.", new_user_session_path, :class => 'btn btn-large' %>
    </p>
  </div>
</div>

app/views/dashboard/shared/_links.html.erb
<% if user_signed_in? %>
  <ul>
    <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
    <li><%= link_to "Edit profile", edit_user_registration_path %></li>
  </ul>
<% else %>
  <ul>
    <li><%= link_to "Sign in", new_user_session_path %></li>
    <li><%= link_to "Register", new_user_registration_path %></li>
  </ul>
<% end %>

app/views/dashboard/shared/_zip_nav.html.erb
  <%= link_to "Add Zipmark", new_mark_path, :class => 'btn btn-primary pull-right' %>

<div class="btn-group">
  <button class="btn">Sort by tag</button>
  <button class="btn dropdown-toggle" data-toggle="dropdown">
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <!-- dropdown menu links -->
    <li><%= link_to "All", root_path %></li>
  <% current_user.owned_tags.each do |tag| %>
    <li><%= link_to tag, tag_path(tag.to_s) %></li>
  <% end %>
  </ul>
</div>

<% if @tag %>
  <div class="btn-group">
    <% if params[:action] == "show_user_tags" %>
      <%= link_to "Just me", tag_path(params[:tag]), :class => "btn active" %>
      <%= link_to "Everyone", all_tag_path(params[:tag]), :class => "btn" %>
    <% elsif params[:action] == "show_all_tags" %>
      <%= link_to "Just me", tag_path(params[:tag]), :class => "btn" %>
      <%= link_to "Everyone", all_tag_path(params[:tag]), :class => "btn active" %>
    <% end %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <hr> </hr>
  Developed and maintained by <a href="mailto:codectc@gmail.com">Cameron Cecil</a>. Check me out on <a href="https://github.com/scrapcode/">GitHub</a>.
</footer>

app/views/layouts/_nav.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <%= link_to "Zipmark", root_path, :class => "brand" %>

      <!-- Nav Links -->
      <div class="nav-collapse collapse">
        <!-- hide everything here -->
        <ul class="nav pull-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Hello, <%= user_signed_in? ? current_user.username : "Guest" %>! <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <% if user_signed_in? %>
                  <li><%= link_to "Settings", edit_user_registration_path %></li>
                  <li><%= link_to "Logoff", destroy_user_session_path, :method => :delete %></li>
                <% else %>
                  <li><%= link_to "Create account", new_user_registration_path %></li>
                  <li><%= link_to "Sign in", new_user_session_path %></li>
                <% end %>
              </ul>
          </li>
        </ul>
      </div>
      <!-- /navlinks -->

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zipmark</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/nav' %>

<div class="container">

  <% flash.each do |name,val| %>
    <% if val.is_a?(String) %>
      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
        <a class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, val, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>

  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-40601208-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</body>
</html>

app/views/marks/_form.html.erb
<% if params[:remote] %>
<div align="center">
<% end %>
<%= form_for(@mark) do |f| %>
  <% if @mark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mark.errors.count, "error") %> occurred.</h2>
      <ul> 
        <% @mark.errors.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field :remote, :value => 'true' if params[:remote] %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, :value => ("#{params[:title]}" or '') %>
  </div>
  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url, :value => ("#{params[:url]}" or '') %>
  </div>

  <div class="field">
    <%= f.label :tag_list, 'Tags' %> <small>(comma seperated)</small><br />
    <%= f.text_field :tag_list, :value => @mark.tag_list, :autofocus => true %>
  </div>

  <div class="actions">
    <%= f.submit "Add Zipmark", :class => 'btn btn-primary btn-large' %>
  </div>

<% end %>
<% if params[:remote] %>
</div>
<% end %>

app/views/marks/_mark.html.erb
<tr>
  <td><%= link_to mark.title, mark.url, :target => '_blank' %></td>
  <td>
    <% mark.tag_list.each do |tag| %>
      <span class="badge badge-info"><%= link_to tag, tag_path(tag.to_s) %></span>
    <% end %>
  </td>
  <td>
    <% if mark.user == current_user %>
      <div class="btn-group">
        <button class="btn btn-mini pull-right dropdown-toggle" data-toggle="dropdown">
          Options <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <!-- dropdown menu links -->
          <li><%= link_to "Delete", mark, :method => :delete, :confirm => "Are you sure?", :class => "btn btn-mini btn-danger" %></li>
        </ul>
      </div>
    <% end %>
  </td>
</tr>

app/views/marks/_show_marks.html.erb
<% if @marks.count > 0 %>
<table class="table table-striped">
  <thead>
    <tr>
      <td width="30%"></td>
      <td width="60%"></td>
      <td width="10%"></td>
    </tr>
  </thead>
  <tbody>
    <%= render @marks %>
  </tbody>
</table>
<% else %>
<div class="container">
  <div class="hero-unit">
    <h1>Let's start Zipmarking.</h1>
    <p>1. Drag the <a href="javascript:(function(){var%20a=window,b=document,c=encodeURIComponent,d=a.open('http://zipmark.herokuapp.com/marks/new/'+c(b.title)+'/'+c(b.location),'bkmk_popup','left='+((a.screenX||a.screenLeft)+10)+',top='+((a.screenY||a.screenTop)+10)+',height=510px,width=550px,resizable=1,alwaysRaised=1');a.setTimeout(function(){d.focus()},300)})();" class="btn btn-large btn-success">Zipmark It!</a> button into your bookmarks toolbar.</p>
    <p>2. Come across something you love, Zipmark it, and I'll save it for later.</p>
    <p>3. Categorize your zipmarks using tags.</p>
    <p>4. See what ohters are zipmarking within the same categories!</p>
  </div>
</div>
<% end %>

app/views/marks/close.html.erb
<script>window.close();</script>

app/views/marks/new.html.erb
<h1>Add Zipmark</h1>

<%= render 'form' %>

<%= link_to 'Back', root_url %>